version: "3.2"
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 2.6
        CHROME_VERSION: 80.0.3987.106-1
        CHROMIUM_DRIVER_VERSION: 80.0.3987.106
    volumes:
      - .:/usr/src/app
